name: FreeBSD-based build

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build in FreeBSD
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        prepare: pkg install -y cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make VERBOSE=1
          make VERBOSE=1 test

    - name: save test report
      if:   failure()
      uses: actions/upload-artifact@v2
      with:
        name: freebsd-test-report
        path: build/Testing/Temporary/LastTest.log
