name: latest Ubuntu-based build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: sudo apt-get install libbsd-dev athena-jot

    - name: create build directory
      run: mkdir build

    - name: build
      working-directory: build
      run: |
        cmake --trace-expand --trace-redirect=CMakeTrace.log -DCMAKE_BUILD_TYPE=Debug ..
        make VERBOSE=1
        make VERBOSE=1 test

    - name: save failures report
      if:   failure()
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-error-report
        path: |
          build/**/*.log
          build/Testing/Temporary/LastTest.log
          build/**/*.expectedout
          build/**/*.stdout
          build/**/*.stderr
