name: latest MacOS-based build

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: create build directory
      run: mkdir build

    - name: build
      working-directory: build
      run: |
        cmake --trace-redirect=CMakeTrace.log -DCMAKE_BUILD_TYPE=Debug ..
        make VERBOSE=1
        make VERBOSE=1 test

    - name: save failures report
      if:   failure()
      uses: actions/upload-artifact@v2
      with:
        name: macos-error-report
        path: |
          build/**/*.log
          build/Testing/Temporary/LastTest.log
          build/**/*.expectedout
          build/**/*.stdout
          build/**/*.stderr
